workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    environment:
      java: 11
      # Commentez ou supprimez les lignes suivantes
      # android_signing:
      #   - keystore_reference
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
