workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    environment:
      java: 11
      android_signing:
        - keystore_reference
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
